version: '3.8'

services:
  app:
    build: .
    container_name: nestjs_app
    restart: always
    ports:
      - "5001:3000"
    environment:
      DATABASE_URL: postgresql://myuser:mypassword@db:5432/mydatabase
      REDIS_HOST: redis  # ✅ now points to Redis container
      REDIS_PORT: 6379
    depends_on:
      - db
      - redis  # ✅ make sure Redis starts before app
    env_file:
      - .env

  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - "6379:6379"  # ✅ expose for BullMQ

volumes:
  pgdata:
